version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      -  /var/www/vendor
    ports:
      - 8181:8181
    env_file:
      - .env.docker
    depends_on:
      - db
    entrypoint:
     - ./docker-entrypoint.sh
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=newsbite
    ports:
      - 3306:3306
volumes:
  db_data: {}


  # post-init:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/var/www
  #     -  /var/www/vendor
  #   depends_on:
  #     - app
  #   command: sh -c "echo 'Waiting for 5 seconds...'; sleep 5; echo 'Running post-init commands...'; php artisan migrate --force && php artisan db:seed --force && php artisan app:news-api-scraper; tail -f /dev/null"    # command: sh -c "echo 'Running post-init commands...'; php artisan migrate; tail -f /dev/null"
