version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      -  /var/www/vendor
    ports:
      - 8181:8181
    env_file:
      - .env.docker
    depends_on:
      - db
    # entrypoint:
    #  - ./docker-entrypoint.sh
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=newsapp
    ports:
      - 3306:3306
volumes:
  db_data: {}